name: "Production Plan"

on:
  pull_request:
    branches: [main]

jobs:
  production-plan:
    runs-on: ubuntu-latest
    environment: production-plan
    env:
      BUILD_ENV: prod
    permissions:
      contents: read
      id-token: write
    concurrency:
      group: production
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHub_Actions_Role_ci
          aws-region: eu-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ./terraform
        run: make init BUILD

      - name: Terraform Validate
        working-directory: ./terraform
        run: make validate ARGS="-no-color"

      - name: Terraform Plan
        working-directory: ./terraform
        run: make plan ARGS="-no-color"
