name: "Production Deploy"

on:
  push:
    branches: [main]

jobs:
  production-deploy:
    runs-on: ubuntu-latest
    environment: production
    env:
      BUILD_ENV: prod
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHub_Actions_Role_cd
          aws-region: eu-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ./terraform
        run: make init

      - name: Terraform Validate
        working-directory: ./terraform
        run: make validate ARGS="-no-color"

      - name: Terraform Plan
        working-directory: ./terraform
        run: make plan ARGS="-no-color"

      - name: Terraform Apply
        working-directory: ./terraform
        run: make apply ARGS="-no-color -auto-approve"
