name: Production Teardown

on:
  workflow_dispatch:
  schedule:
    - cron: "0 21 * * *" # Every day at 9 PM UTC

jobs:
  production-teardown:
    runs-on: ubuntu-latest
    environment: production
    env:
      BUILD_ENV: prod
    permissions:
      contents: read
      id-token: write
    concurrency:
      group: production
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHub_Actions_Role_cd
          aws-region: eu-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ./terraform
        run: make init

      - name: Terraform Apply
        working-directory: ./terraform
        run: make destroy ARGS="-no-color -auto-approve"
